### ISSUE TITLE
fatal imsg_read

### ISSUE THREAD

**Issue by edgarpettijohn** [OpenSMTPD/OpenSMTPD#673]
OpenSMTPD 5.7.3
OpenBSD 5.9
Smtpd dies repeatedly with "fatal imsg_read" 

# smtpd -dv -T imsg
debug: init ssl-tree
info: loading pki information for mail.example1.com
info: loading pki information for mail.example2.com
debug: init ca-tree
info: OpenSMTPD 5.7.3 starting
debug: bounce warning after 1h
debug: bounce warning after 6h
debug: bounce warning after 2d
debug: using "fs" queue backend
debug: using "ramqueue" scheduler backend
debug: using "ram" stat backend
info: startup [debug mode]
debug: parent_send_config_ruleset: reloading
filter: building simple chains...
debug: init ssl-tree
debug: queue: done loading queue into scheduler
debug: parent_send_config: configuring pony process
filter: building simple chain "inbound"
info: loading pki keys for mail.example1.com
debug: parent_send_config: configuring ca process
filter: registering proc "inbound"
info: loading pki keys for mail.example2.com
imsg: lka <- parent: IMSG_CONF_START (len=0)
filter: building complex chains...
imsg: ca <- parent: IMSG_CONF_START (len=0)
imsg: lka <- parent: IMSG_CONF_END (len=0)
filter: done building complex chains
imsg: ca <- parent: IMSG_CONF_END (len=0)
debug: ca_engine_init: using RSA privsep engine
debug: init private ssl-tree
imsg: pony <- parent: IMSG_CONF_START (len=0)
imsg: pony <- parent: IMSG_CONF_END (len=0)
debug: filter "inbound": hooks 0xffffffff flags 0x0000
debug: smtp: listen on XXX.XXX.XXX.XXX port 587 flags 0x469 pki "mail.
debug: smtp: listen on XXX.XXX.XXX.XXX port 25 flags 0x409 pki "mail.p
debug: smtp: listen on XXX.XXX.XXX.XXX port 587 flags 0x469 pki "mail.
debug: smtp: listen on XXX.XXX.XXX.XXX port 25 flags 0x409 pki "mail.i
debug: smtp: listen on 127.0.0.1 port 10029 flags 0x400 pki "" ca ""
debug: smtp: listen on IPv6:fe80::1%lo0 port 10029 flags 0x400 pki "
debug: smtp: listen on IPv6:::1 port 10029 flags 0x400 pki "" ca ""
debug: smtp: listen on 127.0.0.1 port 25 flags 0x400 pki "" ca ""
debug: smtp: listen on IPv6:fe80::1%lo0 port 25 flags 0x400 pki "" c
debug: smtp: listen on IPv6:::1 port 25 flags 0x400 pki "" ca ""
debug: pony: rsae_init
debug: pony: rsae_init
debug: pony: rsae_init
debug: pony: rsae_init
debug: smtp: will accept at most 497 clients
debug: smtpd: scanning offline queue...
debug: smtpd: offline scanning done
debug: smtp: new client on listener: 0x12625198d000
imsg: lka <- pony: IMSG_SMTP_DNS_PTR (len=34)
imsg: pony <- lka: IMSG_SMTP_DNS_PTR (len=33)
imsg: lka <- pony: IMSG_SMTP_LOOKUP_HELO (len=42)
debug: lka: helo hnames:XXX.XXX.XXX.XXX
imsg: pony <- lka: IMSG_SMTP_LOOKUP_HELO (len=38)
smtp-in: session 243bc7883cefcd0c: connection from host lists.openbsd.org [192.43.244.163] established
imsg: lka <- pony: IMSG_SMTP_TLS_INIT (len=272)
debug: lka: looking up pki "mail.example1.com"
imsg: pony <- lka: IMSG_SMTP_TLS_INIT (len=2224)
debug: session_start_ssl: switching to SSL
debug: pony: rsae_priv_enc
imsg: ca <- pony: IMSG_CA_PRIVENC (len=143)
fatal: imsg_read
warn: parent -> pony: pipe closed
warn: lka -> pony: pipe closed
warn: queue -> pony: pipe closed
warn: control -> pony: pipe closed
warn: ca -> pony: pipe closed
warn: inbound -> filter: pipe closed
warn: table-api: pipe closed
warn: scheduler -> queue: pipe closed

*adding additional log snippet*
smtp-in: session 0e0b655d303fc315: connection from host lists.openbsd.org [192.43.244.163] established
imsg: lka <- pony: IMSG_SMTP_TLS_INIT (len=272)
debug: lka: looking up pki "mail.exampl1.com"
imsg: pony <- lka: IMSG_SMTP_TLS_INIT (len=2224)
debug: session_start_ssl: switching to SSL
debug: pony: rsae_priv_enc
imsg: ca <- pony: IMSG_CA_PRIVENC (len=143)
debug: SSL library error: io_dispatch_accept_ssl:SSL_accept: error:1409B006:SSL routines:SSL3_SEND_SERVER_KEY_EXCHANGE:EVP lib
smtp-in: session 0e0b655d303fc315: connection from host lists.openbsd.org [192.43.244.163] closed (IO error: error:1409B006:SSL routines:SSL3_SEND_SERVER_KEY_EXCHANGE:EVP lib)
debug: smtp: 0x66cbe079000: deleting session: IO error
imsg: pony <- ca: IMSG_CA_PRIVENC (len=535)
smtpd: session_imsg: unexpected IMSG_CA_PRIVENC imsg
warn: ca -> pony: pipe closed

Changed fatalx("imsg_read") to abort() to get a dump
(gdb) backtrace
#0  0x000001fb8abd487a in thrkill () at <stdin>:2
#1  0x000001fb8abcff39 in *_libc_abort ()
    at /usr/src/lib/libc/stdlib/abort.c:52
#2  0x000001f95e50c58b in ?? () from /usr/sbin/smtpd
#3  0x000001fc270574b0 in RSA_sign (type=674, 
 m=0x1fbacb45400 "0Q0\r\006\t`\206H\001e\003\004\002\003\005", m_len=Variable "m_len" is not available.
)
    at /usr/src/lib/libcrypto/crypto/../../libssl/src/crypto/rsa/rsa_sign.c:133
#4  0x000001fc26ffb42f in pkey_rsa_sign (ctx=0x1fc2a277600, 
    sig=0x1fc5319d04d "0\f\006\003U\004\a\f\005Alvin1\0370\035\006\003U\004\003\f\026mail.example1.com1&0$\006\t*\206H\206ï¿½\r\001\t\001\026\027edgar@example1.com0\036\027\r160215231054Z\027\r170214231054Z0v1\v0\t\006\003U\004\006\023\002US1\0160\f\006\003U\004\b\f\005Texas1\0160\f\006\003U\004\a\f\005Alvin1\0370\035\006\003U\004\003\f\026mail.example1.com1"..., 
    siglen=0x7f7ffffe97e0, tbs=0x7f7ffffe97f0 "\0248\234Y\037\202ï¿½\fï¿½$", 
    tbslen=64)
    at /usr/src/lib/libcrypto/crypto/../../libssl/src/crypto/rsa/rsa_pmeth.c:192
#5  0x000001fc27045fc1 in EVP_SignFinal (ctx=0x7f7ffffe98e0, 
    sigret=0x1fc5319d04d "0\f\006\003U\004\a\f\005Alvin1\0370\035\006\003U\004\003\f\026mail.example1.com1&0$\006\t*\206H\206ï¿½\r\001\t\001\026\027edgar@example1.com0\036\027\r160215231054Z\027\r170214231054Z0v1\v0\t\006\003U\004\006\023\002US1\0160\f\006\003U\004\b\f\005Texas1\0160\f\006\003U\004\a\f\005Alvin1\0370\035\006\003U\004\003\f\026mail.example1.com1"..., 
    siglen=0x7f7ffffe9948, pkey=Variable "pkey" is not available.
)
    at /usr/src/lib/libcrypto/crypto/../../libssl/src/crypto/evp/p_sign.c:94
#6  0x000001fc00f5779c in ssl3_send_server_key_exchange (s=0x1fbcf1c9400)
    at /usr/src/lib/libssl/ssl/../../libssl/src/ssl/s3_srvr.c:1486
#7  0x000001fc00f590dd in ssl3_accept (s=0x1fbcf1c9400)
    at /usr/src/lib/libssl/ssl/../../libssl/src/ssl/s3_srvr.c:356
#8  0x000001fc00f5438e in ssl23_get_client_hello (s=0x1fbcf1c9400)
    at /usr/src/lib/libssl/ssl/../../libssl/src/ssl/s23_srvr.c:501
#9  0x000001fc00f54986 in ssl23_accept (s=0x1fbcf1c9400)
    at /usr/src/lib/libssl/ssl/../../libssl/src/ssl/s23_srvr.c:175
#10 0x000001f95e51847f in ?? () from /usr/sbin/smtpd
#11 0x000001fb9fab6f88 in event_base_loop (base=0x1fb859ea000, flags=Variable "flags" is not available.
)
    at /usr/src/lib/libevent/event.c:350
#12 0x000001f95e52faad in SSL_CTX_use_certificate_chain_mem ()   from /usr/sbin/smtpd
#13 0x000001f95e53dbe2 in imsg_dispatch () from /usr/sbin/smtpd
---Type <return> to continue, or q <return> to quit--- 
#14 0x000001f95e509861 in ?? () from /usr/sbin/smtpd
#15 0x0000000000000000 in ?? ()

If you need more info just let me know.

**Comment by edgarpettijohn** [comment]
I had reverted back to 5.7.3 because of problems after upgrading to OpenBSD 5.9 however those problems seem to have been PKG_PATH related :) 

Closing for now.
